"""Machine-readable marking of synthetic content, read and written from bytes.

Design note D-60, and the reason this module exists at all.

Article 50(2) of the AI Act requires providers of AI systems that generate
synthetic audio, image, video or text to mark the output in a machine-readable
format and make it detectable as artificially generated or manipulated. It is
the rare obligation in this Regulation that is genuinely decidable by reading a
file: either a marking is present and parseable, or it is not. That is why this
module is deterministic and why the control built on it is the only place in
Actaira where a governance answer comes from bytes rather than from a document
somebody wrote.

**What "machine-readable" resolves to in practice.** The Regulation names no
format, so a tool that invents one is guessing. Two real ones exist and this
module reads both:

  * **IPTC `DigitalSourceType`**, an XMP property whose value is a controlled
    vocabulary term. `trainedAlgorithmicMedia` means the asset was created by a
    generative model; `compositeWithTrainedAlgorithmicMedia` means a model
    contributed part of it. This is the vocabulary C2PA itself references for
    the same purpose, it is one XMP property, and it is what this module
    *writes*, because writing a full C2PA manifest without a signing identity
    would produce a provenance claim nobody can check.
  * **C2PA / JUMBF**, a signed provenance manifest embedded in the file. This
    module *detects* it, parses the box structure enough to report that a
    manifest is present and how large it is, and stops there. It does not
    validate the manifest's signature.

That asymmetry is deliberate and it is the doctrine of this repository applied
to a new surface: detecting a C2PA box tells you a manifest is present, which
is a true and useful fact, and claiming it is *valid* would require a trust
store this project does not ship. So a C2PA box is reported as
`present_unverified`, never as a verified provenance claim, in exactly the way
the RFC 3161 path reports an unverified TSA chain.

**What this module refuses to do.** It does not detect watermarks in pixels or
in audio samples. Statistical watermarking is a real family of techniques and
it is not readable without the detector key held by whoever embedded it, so a
tool that claimed to check for watermarks in general would be claiming to
detect what it cannot see. `detect()` reports the mechanisms it looked for, by
name, so a reader can tell an absent marking from an unlooked-for one, and an
artifact whose marking could only be a pixel watermark comes back
`INCONCLUSIVE` rather than unmarked.

**The measured result this module exists to produce.** Metadata markings are
fragile: a re-encode, a format conversion or a metadata strip removes them, and
every one of those happens routinely when an image passes through a social
platform or a CMS. `evals/marking/` measures exactly that, transformation by
transformation, and publishes the survival matrix. The honest headline is not
"Actaira marks your content"; it is "here is how often the legally required
marking survives the pipeline your content actually goes through", which is a
number the obligation's own drafters would want and which this repository
could find nobody publishing.
"""
from __future__ import annotations

import re
import struct
import zlib
from collections.abc import Sequence
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# The vocabulary. Values are IRIs from the IPTC NewsCodes scheme, written in
# full because the short form is ambiguous outside its namespace binding.
# ---------------------------------------------------------------------------
IPTC_SCHEME = "http://cv.iptc.org/newscodes/digitalsourcetype/"
TRAINED_ALGORITHMIC_MEDIA = IPTC_SCHEME + "trainedAlgorithmicMedia"
COMPOSITE_WITH_TRAINED = IPTC_SCHEME + "compositeWithTrainedAlgorithmicMedia"
ALGORITHMIC_MEDIA = IPTC_SCHEME + "algorithmicMedia"

# The terms that answer Article 50(2) affirmatively: the asset is wholly or
# partly the output of a generative model. `algorithmicMedia` is deliberately
# NOT on this list. It covers content produced by an algorithm that is not a
# trained model (a chart renderer, a procedural texture), which is not what the
# Article is about, and treating it as a positive would let a marking that says
# "drawn by software" pass for one that says "generated by a model".
SYNTHETIC_TERMS = frozenset({TRAINED_ALGORITHMIC_MEDIA, COMPOSITE_WITH_TRAINED})

XMP_NS_URI = "http://ns.adobe.com/xap/1.0/"
XMP_HEADER = XMP_NS_URI.encode("ascii") + b"\x00"
PNG_XMP_KEYWORD = b"XML:com.adobe.xmp"

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
JPEG_SOI = b"\xff\xd8"

# Bound on how much of a file this module will read looking for metadata. A
# marking lives in the header, so a cap that covers the first few megabytes
# finds every real one while refusing to walk a multi-gigabyte video. Chosen
# from measurement rather than taste: the largest XMP packet in the eval corpus
# is 4 KiB and the largest C2PA manifest measured is 1.9 MiB.
MAX_METADATA_SCAN_BYTES = 16 << 20
# A single XMP packet larger than this is not a marking, it is a payload, and
# parsing it would be work an attacker chose for us.
MAX_XMP_BYTES = 4 << 20


class Mechanism(str, Enum):
    """How a marking was carried, kept in the output because it decides fragility."""

    XMP_IPTC = "xmp_iptc_digitalsourcetype"
    PNG_TEXT = "png_text_chunk"
    C2PA_JUMBF = "c2pa_jumbf"
    NONE = "none"


class MarkingState(str, Enum):
    """Four states, and the third is the one most tools omit.

    MARKED             a machine-readable marking was parsed and it says the
                       asset is wholly or partly model-generated.
    MARKED_OTHER       a marking was parsed and it says something else (for
                       example `algorithmicMedia`). Present but not responsive
                       to Article 50(2), which is a different fact from absent.
    UNMARKED           the file was read, every mechanism this module knows was
                       looked for, and none was found.
    INCONCLUSIVE       the file could not be read far enough to say, or its
                       format admits only mechanisms this module cannot read.
    """

    MARKED = "marked"
    MARKED_OTHER = "marked_other"
    UNMARKED = "unmarked"
    INCONCLUSIVE = "inconclusive"


@dataclass(frozen=True)
class MarkingReport:
    path: str
    container: str
    state: MarkingState
    mechanisms_found: tuple[Mechanism, ...] = ()
    mechanisms_searched: tuple[Mechanism, ...] = ()
    terms: tuple[str, ...] = ()
    c2pa_bytes: int = 0
    reason: str = ""
    detail: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "container": self.container,
            "state": self.state.value,
            "mechanisms_found": [m.value for m in self.mechanisms_found],
            "mechanisms_searched": [m.value for m in self.mechanisms_searched],
            "terms": list(self.terms),
            "c2pa_bytes": self.c2pa_bytes,
            "reason": self.reason,
            "detail": self.detail,
        }


# ---------------------------------------------------------------------------
# Container sniffing, by content. Same doctrine as formats/detect.py: the file
# name is a claim, the magic number is a fact.
# ---------------------------------------------------------------------------
def container_of(head: bytes) -> str:
    if head.startswith(PNG_SIGNATURE):
        return "png"
    if head.startswith(JPEG_SOI):
        return "jpeg"
    if len(head) >= 12 and head[4:8] == b"ftyp":
        return "bmff"
    if head.startswith(b"RIFF") and len(head) >= 12 and head[8:12] == b"WEBP":
        return "webp"
    if head.startswith(b"%PDF-"):
        return "pdf"
    if head.startswith(b"ID3") or head.startswith(b"\xff\xfb"):
        return "mp3"
    if head.startswith(b"RIFF") and len(head) >= 12 and head[8:12] == b"WAVE":
        return "wav"
    return "unknown"


def detect(path: Path) -> MarkingReport:
    """Read one file and report whether it carries a machine-readable marking."""
    path = Path(path)
    try:
        with path.open("rb") as handle:
            head = handle.read(64)
            blob = head + handle.read(MAX_METADATA_SCAN_BYTES - len(head))
    except OSError as exc:
        return MarkingReport(
            path=path.name,
            container="unknown",
            state=MarkingState.INCONCLUSIVE,
            reason=f"unreadable: {type(exc).__name__}",
        )

    container = container_of(head)
    if container == "png":
        return _detect_png(path.name, blob)
    if container == "jpeg":
        return _detect_jpeg(path.name, blob)
    if container in ("bmff", "webp", "pdf"):
        return _detect_generic(path.name, container, blob)
    # Audio and unknown containers: the only marking mechanism that would apply
    # is one this module cannot read, so saying "unmarked" would be a claim
    # about a place it never looked.
    return MarkingReport(
        path=path.name,
        container=container,
        state=MarkingState.INCONCLUSIVE,
        mechanisms_searched=(),
        reason="container_not_supported_for_marking_detection",
    )


# ---------------------------------------------------------------------------
# PNG
# ---------------------------------------------------------------------------
def iter_png_chunks(blob: bytes):
    """Yield (type, data, offset) for each PNG chunk. Tolerates truncation.

    A truncated file is common in the fuzz corpus and must not raise: the
    caller needs "I could not read past here", which is INCONCLUSIVE, not an
    exception that the control layer would have to turn into one anyway.
    """
    offset = len(PNG_SIGNATURE)
    while offset + 8 <= len(blob):
        (length,) = struct.unpack(">I", blob[offset : offset + 4])
        chunk_type = blob[offset + 4 : offset + 8]
        start = offset + 8
        end = start + length
        if length > len(blob) or end > len(blob):
            return
        yield chunk_type, blob[start:end], offset
        offset = end + 4  # skip CRC
        if chunk_type == b"IEND":
            return


def _detect_png(name: str, blob: bytes) -> MarkingReport:
    searched = (Mechanism.XMP_IPTC, Mechanism.PNG_TEXT, Mechanism.C2PA_JUMBF)
    found: list[Mechanism] = []
    terms: list[str] = []
    c2pa_bytes = 0
    truncated = True

    for chunk_type, data, _offset in iter_png_chunks(blob):
        if chunk_type == b"IEND":
            truncated = False
        if chunk_type == b"caBX":
            found.append(Mechanism.C2PA_JUMBF)
            c2pa_bytes = len(data)
        elif chunk_type in (b"iTXt", b"tEXt", b"zTXt"):
            keyword, text = _png_text_payload(chunk_type, data)
            if text is None:
                continue
            if keyword == PNG_XMP_KEYWORD:
                packet_terms = _terms_in_xmp(text)
                if packet_terms:
                    found.append(Mechanism.XMP_IPTC)
                    terms.extend(packet_terms)
            else:
                packet_terms = _terms_in_xmp(text)
                if packet_terms:
                    found.append(Mechanism.PNG_TEXT)
                    terms.extend(packet_terms)

    if truncated and not found:
        return MarkingReport(
            path=name,
            container="png",
            state=MarkingState.INCONCLUSIVE,
            mechanisms_searched=searched,
            reason="png_truncated_before_iend",
        )
    return _verdict(name, "png", found, terms, searched, c2pa_bytes)


def _png_text_payload(chunk_type: bytes, data: bytes) -> tuple[bytes, bytes | None]:
    """The keyword and the decoded text of a PNG text chunk, or (keyword, None)."""
    if b"\x00" not in data:
        return b"", None
    keyword, _, rest = data.partition(b"\x00")
    try:
        if chunk_type == b"tEXt":
            return keyword, rest
        if chunk_type == b"zTXt":
            if not rest:
                return keyword, None
            # rest = compression method (1 byte) + compressed text
            return keyword, zlib.decompress(rest[1:])[:MAX_XMP_BYTES]
        # iTXt: compression flag, compression method, language tag \0,
        # translated keyword \0, text
        if len(rest) < 2:
            return keyword, None
        compressed = rest[0] == 1
        remainder = rest[2:]
        parts = remainder.split(b"\x00", 2)
        if len(parts) < 3:
            return keyword, None
        text = parts[2]
        if compressed:
            text = zlib.decompress(text)[:MAX_XMP_BYTES]
        return keyword, text[:MAX_XMP_BYTES]
    except (zlib.error, IndexError):
        return keyword, None


# ---------------------------------------------------------------------------
# JPEG
# ---------------------------------------------------------------------------
def iter_jpeg_segments(blob: bytes):
    """Yield (marker, payload) for each JPEG APPn/COM segment before SOS."""
    offset = 2
    while offset + 4 <= len(blob):
        if blob[offset] != 0xFF:
            return
        marker = blob[offset + 1]
        if marker in (0xD8, 0xD9):
            offset += 2
            continue
        if marker == 0xDA:  # start of scan: entropy-coded data follows
            return
        (length,) = struct.unpack(">H", blob[offset + 2 : offset + 4])
        if length < 2:
            return
        start = offset + 4
        end = offset + 2 + length
        if end > len(blob):
            return
        yield marker, blob[start:end]
        offset = end


def _detect_jpeg(name: str, blob: bytes) -> MarkingReport:
    searched = (Mechanism.XMP_IPTC, Mechanism.C2PA_JUMBF)
    found: list[Mechanism] = []
    terms: list[str] = []
    c2pa_bytes = 0

    for marker, payload in iter_jpeg_segments(blob):
        if marker == 0xE1 and payload.startswith(XMP_HEADER):
            packet = payload[len(XMP_HEADER) :][:MAX_XMP_BYTES]
            packet_terms = _terms_in_xmp(packet)
            if packet_terms:
                found.append(Mechanism.XMP_IPTC)
                terms.extend(packet_terms)
        elif marker == 0xEB:  # APP11, where JUMBF/C2PA lives
            if b"jumb" in payload[:64] or payload[:2] == b"JP":
                found.append(Mechanism.C2PA_JUMBF)
                c2pa_bytes += len(payload)
    return _verdict(name, "jpeg", found, terms, searched, c2pa_bytes)


# ---------------------------------------------------------------------------
# Generic containers: look for the packet, do not pretend to parse the format
# ---------------------------------------------------------------------------
def _detect_generic(name: str, container: str, blob: bytes) -> MarkingReport:
    """A byte scan, declared as such.

    For BMFF, WebP and PDF this module does not implement the container's box
    or object structure. It looks for an XMP packet and for a JUMBF signature
    in the bytes it read. That finds a real marking and can in principle be
    fooled by those bytes appearing somewhere they are not a marking, so the
    result carries `scan_only: True` and the control that consumes it never
    treats a positive here as strong as a parsed one.
    """
    searched = (Mechanism.XMP_IPTC, Mechanism.C2PA_JUMBF)
    found: list[Mechanism] = []
    terms = _terms_in_xmp(blob)
    if terms:
        found.append(Mechanism.XMP_IPTC)
    c2pa_bytes = 0
    if b"jumb" in blob and b"c2pa" in blob:
        found.append(Mechanism.C2PA_JUMBF)
        c2pa_bytes = blob.count(b"jumb")
    report = _verdict(name, container, found, terms, searched, c2pa_bytes)
    return MarkingReport(
        path=report.path,
        container=report.container,
        state=report.state,
        mechanisms_found=report.mechanisms_found,
        mechanisms_searched=report.mechanisms_searched,
        terms=report.terms,
        c2pa_bytes=report.c2pa_bytes,
        reason=report.reason,
        detail={"scan_only": True},
    )


_TERM_PATTERN = re.compile(
    rb"http://cv\.iptc\.org/newscodes/digitalsourcetype/([A-Za-z]+)"
)


def _terms_in_xmp(blob: bytes) -> tuple[str, ...]:
    """Every IPTC digitalSourceType IRI in a byte range, in order of appearance."""
    if not blob:
        return ()
    return tuple(IPTC_SCHEME + m.group(1).decode("ascii") for m in _TERM_PATTERN.finditer(blob))


def _verdict(
    name: str,
    container: str,
    # Read, never mutated, and the callers pass a list in one place and a
    # tuple in another. Sequence is what this function actually needs.
    found: Sequence[Mechanism],
    terms: Sequence[str],
    searched: tuple[Mechanism, ...],
    c2pa_bytes: int,
) -> MarkingReport:
    unique_found = tuple(dict.fromkeys(found))
    unique_terms = tuple(dict.fromkeys(terms))
    if any(term in SYNTHETIC_TERMS for term in unique_terms):
        state = MarkingState.MARKED
    elif Mechanism.C2PA_JUMBF in unique_found:
        # A C2PA manifest is present. Its assertions are not parsed and its
        # signature is not checked, so this is "a provenance claim exists",
        # which is not the same as "it says the asset is synthetic".
        state = MarkingState.MARKED_OTHER
    elif unique_terms:
        state = MarkingState.MARKED_OTHER
    else:
        state = MarkingState.UNMARKED
    reason = ""
    if state is MarkingState.MARKED_OTHER and Mechanism.C2PA_JUMBF in unique_found:
        reason = "c2pa_manifest_present_unverified"
    elif state is MarkingState.MARKED_OTHER:
        reason = "marking_present_but_not_a_synthetic_term"
    return MarkingReport(
        path=name,
        container=container,
        state=state,
        mechanisms_found=unique_found or (Mechanism.NONE,),
        mechanisms_searched=searched,
        terms=unique_terms,
        c2pa_bytes=c2pa_bytes,
        reason=reason,
    )


# ---------------------------------------------------------------------------
# Writing a marking
# ---------------------------------------------------------------------------
XMP_TEMPLATE = """<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
    xmlns:dc="http://purl.org/dc/elements/1.1/">
   <Iptc4xmpExt:DigitalSourceType>{term}</Iptc4xmpExt:DigitalSourceType>
   <dc:description>{note}</dc:description>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"""


def build_xmp(term: str = TRAINED_ALGORITHMIC_MEDIA, note: str = "") -> bytes:
    """The XMP packet Actaira writes. One property, plus a human-readable line.

    Kept minimal on purpose. Every additional property is another thing a
    downstream tool can disagree with, and Article 50(2) asks for the asset to
    be marked and detectable, not for a provenance record. The one property is
    the machine-readable part; `dc:description` is the human-readable courtesy
    that survives in tools that show captions but not custom namespaces.
    """
    if term not in (TRAINED_ALGORITHMIC_MEDIA, COMPOSITE_WITH_TRAINED, ALGORITHMIC_MEDIA):
        raise ValueError(f"not an IPTC digitalSourceType IRI: {term!r}")
    safe_note = (note or "Generated or modified with an AI system.").replace("<", "").replace(">", "")
    return XMP_TEMPLATE.format(term=term, note=safe_note).encode("utf-8")


def mark_png(blob: bytes, term: str = TRAINED_ALGORITHMIC_MEDIA, note: str = "") -> bytes:
    """Insert an XMP iTXt chunk after IHDR, replacing any existing XMP chunk.

    Replacing rather than appending: two XMP packets in one file is a state no
    reader resolves the same way, and a marking whose meaning depends on which
    chunk the reader picked is not machine-readable in any useful sense.
    """
    if not blob.startswith(PNG_SIGNATURE):
        raise ValueError("not a PNG")
    packet = build_xmp(term, note)
    payload = (
        PNG_XMP_KEYWORD
        + b"\x00"
        + b"\x00"  # compression flag: uncompressed
        + b"\x00"  # compression method
        + b"\x00"  # language tag (empty)
        + b"\x00"  # translated keyword (empty)
        + packet
    )
    new_chunk = _png_chunk(b"iTXt", payload)

    out = bytearray(PNG_SIGNATURE)
    inserted = False
    for chunk_type, data, _offset in iter_png_chunks(blob):
        if chunk_type in (b"iTXt", b"tEXt", b"zTXt"):
            keyword, _ = _png_text_payload(chunk_type, data)
            if keyword == PNG_XMP_KEYWORD:
                continue  # drop the old packet
        out += _png_chunk(chunk_type, data)
        if chunk_type == b"IHDR" and not inserted:
            out += new_chunk
            inserted = True
    if not inserted:
        raise ValueError("PNG has no IHDR")
    return bytes(out)


def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + chunk_type
        + data
        + struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
    )


def mark_jpeg(blob: bytes, term: str = TRAINED_ALGORITHMIC_MEDIA, note: str = "") -> bytes:
    """Insert an APP1 XMP segment after SOI, replacing any existing XMP segment.

    A JPEG APP segment payload is bounded by a 16-bit length, so the packet has
    to fit in 65533 bytes minus the namespace header. The packet this module
    builds is about 600 bytes; the check exists because a caller passing a long
    note would otherwise produce a file that decoders reject, and a marking
    that breaks the asset is worse than no marking.
    """
    if not blob.startswith(JPEG_SOI):
        raise ValueError("not a JPEG")
    packet = build_xmp(term, note)
    payload = XMP_HEADER + packet
    if len(payload) + 2 > 0xFFFF:
        raise ValueError("XMP packet too large for one APP1 segment")
    segment = b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload

    out = bytearray(JPEG_SOI)
    body = blob[2:]
    # Drop an existing XMP APP1 if there is one, keeping every other segment.
    offset = 0
    rebuilt = bytearray()
    for marker, seg_payload in iter_jpeg_segments(blob):
        raw = b"\xff" + bytes([marker]) + struct.pack(">H", len(seg_payload) + 2) + seg_payload
        if marker == 0xE1 and seg_payload.startswith(XMP_HEADER):
            offset += len(raw)
            continue
        rebuilt += raw
        offset += len(raw)
    tail = body[offset:]
    out += segment + bytes(rebuilt) + tail
    return bytes(out)


def mark_file(path: Path, term: str = TRAINED_ALGORITHMIC_MEDIA, note: str = "") -> bytes:
    blob = Path(path).read_bytes()
    container = container_of(blob[:64])
    if container == "png":
        return mark_png(blob, term, note)
    if container == "jpeg":
        return mark_jpeg(blob, term, note)
    raise ValueError(f"marking is implemented for png and jpeg, not {container}")


def strip_marking(blob: bytes) -> bytes:
    """Remove every marking this module can write. Used by the robustness eval.

    Present because the eval has to model a hostile or careless pipeline, and a
    stripper written from the same table as the writer is the only one that can
    be trusted to remove exactly what the writer put there.
    """
    container = container_of(blob[:64])
    if container == "png":
        out = bytearray(PNG_SIGNATURE)
        for chunk_type, data, _offset in iter_png_chunks(blob):
            if chunk_type in (b"iTXt", b"tEXt", b"zTXt", b"caBX"):
                continue
            out += _png_chunk(chunk_type, data)
        return bytes(out)
    if container == "jpeg":
        out = bytearray(JPEG_SOI)
        offset = 0
        for marker, payload in iter_jpeg_segments(blob):
            raw = b"\xff" + bytes([marker]) + struct.pack(">H", len(payload) + 2) + payload
            offset += len(raw)
            if marker in (0xE1, 0xEB) and (
                payload.startswith(XMP_HEADER) or b"jumb" in payload[:64]
            ):
                continue
            out += raw
        return bytes(out) + blob[2 + offset :]
    return blob
