#!/usr/bin/env bash
# Regenerate the RFC 3161 fixtures in this directory.
#
# Why fixtures at all: the test suite must never depend on a network, and a
# timestamp authority is by definition somebody else's machine. Why fixtures
# generated by OpenSSL rather than by Seamark: a test that builds its inputs
# with the code under test proves only that the code agrees with itself.
# These bytes were written by an implementation this project did not write,
# so `tests/test_timestamp.py` is a cross-implementation check.
#
# What is here, and what is deliberately not:
#
#   subject.bin                 the document the tokens are over
#   other.bin                   a different document, for the mismatch case
#   query_cert_nononce.tsq      OpenSSL's own TimeStampReq, byte-compared
#   query_nocert_nononce.tsq    the same without certReq
#   granted.tsr                 a granted response carrying the signer chain
#   granted_no_cert.tsr         granted, no certificate: nothing to check against
#   granted_other_subject.tsr   granted, but over other.bin
#   rejection.tsr               a real PKIStatus 2 rejection (bad policy)
#   ca.crt, tsa.crt             the throwaway certificates, for inspection
#
# The TSA private key is NOT in the repository and never should be. Run this
# script to make a new one; the genTime of the regenerated tokens will be the
# moment you run it, and no test asserts a fixed date, precisely so that
# regenerating stays cheap.
#
# Requires: openssl 3.x. Run from this directory:  bash generate.sh
set -euo pipefail
cd "$(dirname "$0")"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

openssl req -x509 -newkey rsa:2048 -nodes -keyout "$work/ca.key" -out ca.crt -days 7300 \
  -subj "/C=ES/O=Actaira Test Fixtures/CN=Actaira Fixture Root CA" \
  -addext "basicConstraints=critical,CA:TRUE" \
  -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null

openssl req -newkey rsa:2048 -nodes -keyout "$work/tsa.key" -out "$work/tsa.csr" \
  -subj "/C=ES/O=Actaira Test Fixtures/CN=Actaira Fixture TSA" 2>/dev/null

cat > "$work/tsa_ext.cnf" <<'EXT'
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature,nonRepudiation
extendedKeyUsage=critical,timeStamping
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer
EXT
openssl x509 -req -in "$work/tsa.csr" -CA ca.crt -CAkey "$work/ca.key" -CAcreateserial \
  -out tsa.crt -days 7300 -extfile "$work/tsa_ext.cnf" -sha256 2>/dev/null

cat > "$work/tsa.cnf" <<EXT
[ tsa ]
default_tsa = tsa_config1

[ tsa_config1 ]
serial = $work/tsa_serial
crypto_device = builtin
signer_cert = $PWD/tsa.crt
certs = $PWD/ca.crt
signer_key = $work/tsa.key
signer_digest = sha256
default_policy = 1.3.6.1.4.1.99999.1.1
other_policies = 1.3.6.1.4.1.99999.1.2
digests = sha256, sha384, sha512
accuracy = secs:1, millisecs:500
clock_precision_digits = 0
ordering = yes
tsa_name = yes
ess_cert_id_chain = no
EXT
echo 01 > "$work/tsa_serial"

printf 'actaira rfc3161 test subject\nthis file stands in for the pre-anchor manifest\n' > subject.bin
printf 'a different document entirely\n' > other.bin

openssl ts -query -data subject.bin -sha256 -cert -no_nonce -out query_cert_nononce.tsq
openssl ts -query -data subject.bin -sha256 -no_nonce -out query_nocert_nononce.tsq
openssl ts -query -data subject.bin -sha256 -cert -out "$work/nonce.tsq"
openssl ts -query -data other.bin -sha256 -cert -no_nonce -out "$work/other.tsq"
openssl ts -query -data subject.bin -sha256 -tspolicy 1.2.3.4.5.6 -no_nonce -out "$work/badpolicy.tsq"

openssl ts -reply -config "$work/tsa.cnf" -queryfile "$work/nonce.tsq" -out granted.tsr 2>/dev/null
openssl ts -reply -config "$work/tsa.cnf" -queryfile query_nocert_nononce.tsq -out granted_no_cert.tsr 2>/dev/null
openssl ts -reply -config "$work/tsa.cnf" -queryfile "$work/other.tsq" -out granted_other_subject.tsr 2>/dev/null
openssl ts -reply -config "$work/tsa.cnf" -queryfile "$work/badpolicy.tsq" -out rejection.tsr 2>/dev/null || true

openssl ts -verify -data subject.bin -in granted.tsr -CAfile ca.crt -untrusted tsa.crt

rm -f ca.srl
echo "fixtures regenerated"
