#!/usr/bin/env python3
"""Write `docs/RULES.md` from the rule packs the package ships.

Design note D-278. The same argument as `contracts_doc.py`: a page typed by
hand is another place a fact is recorded, and the one nothing would notice going
stale. So the rule table is generated, `make rules` regenerates it, and
`release_check.rules_are_documented` compares the file on disk against what this
script would write - which is the check that document asked for in its own
docstring and could not have until phase S1 gave it a page to point at.

    python3 scripts/rules_doc.py            # rewrite docs/RULES.md
    python3 scripts/rules_doc.py --check    # fail if it would differ

The page carries no count of anything, no ordering by severity and no totals. A
severity in the table is the label its author wrote, in the author's column,
beside the author's name.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

PAGE = ROOT / "docs" / "RULES.md"

HEADER = """# Rules

Generated by `scripts/rules_doc.py`; run `make rules` after changing a pack. Do
not edit this file by hand: `make release-check` rewrites it into a temporary
path and fails when the two differ.

Every rule below compares an observed fact against a condition a person wrote
down. None of them says what a configuration would do, and none answers `False`
about a fact nobody observed: the clauses name the facts a rule needs, and a
capability that does not carry one comes back INDETERMINATE.

**`severity` is the label the rule's author chose.** It is published beside that
author's name and is never summed, maximised or compared with another pack's.
Actaira computes no number about it.

**A rule identifier means one thing forever.** `docs/COMPATIBILITY.md` promises
that identifiers are never renumbered and never reused for a different finding.

`requires` is the least a capability must be resolved to before the rule
answers: `DECLARED` means the rule reports what a file says, whether or not it
is in force; `EFFECTIVE` means it answers only once the scopes resolve.

**A rule marked NO REAL VIOLATION has no violating case from a real public
configuration.** CLAUDE.md requires a rule's two tests to run on a real
configuration or on a reconstruction cited from an incident report; a third,
narrow branch admits the vendor's own published configuration when the rule's
scope makes a public sample impossible, or when a recorded search found none.
The mark is published here, in the table and under the rule, because a reader of
this page has to be able to see which rules that applies to without going to
look for a fixture's provenance file. Each marked rule shows either the page its
case comes from, with the digest of that page and the date it was read, or the
searches that came back empty.
"""

COLUMNS = (
    "| Rule | Capability | Requires | Severity (author's label) | Author | Pack | Version "
    "| Violating case |\n"
    "|---|---|---|---|---|---|---|---|\n"
)


def render() -> str:
    from actaira.i18n.catalog import Catalog
    from actaira.surface import rules as rule_module

    english = Catalog("en")
    spanish = Catalog("es")
    catalogue = rule_module.load()

    out = [HEADER]
    by_pack: dict[str, list] = {}
    for rule in catalogue:
        by_pack.setdefault(rule.pack, []).append(rule)

    for pack in sorted(by_pack):
        out.append(f"\n## Pack `{pack}`\n\n")
        out.append(COLUMNS)
        for rule in by_pack[pack]:
            out.append(
                "| [`{id}`](#{anchor}) | `{capability}` | {requires} | {severity} | {author} "
                "| {pack} | {version} | {sample} |\n".format(
                    id=rule.id,
                    anchor=rule.id.lower(),
                    capability="`, `".join(rule.capability),
                    requires=rule.requires.name,
                    severity=rule.severity,
                    author=rule.author,
                    pack=rule.pack,
                    version=rule.version,
                    sample="**NO REAL VIOLATION**" if rule.marked else "real",
                )
            )

    out.append("\n## Each rule\n")
    for rule in catalogue:
        out.append(f"\n### {rule.id}\n\n")
        out.append(f"{english.rule(rule.id)}\n\n")
        out.append(f"*Español:* {spanish.rule(rule.id)}\n\n")
        out.append(f"- **Vendor**: `{rule.vendor}`\n")
        out.append("- **Capability**: `{}`\n".format("`, `".join(rule.capability)))
        out.append(f"- **Requires**: {rule.requires.name}\n")
        out.append(
            f"- **Severity**: {rule.severity} — the label written by {rule.author}, never combined with another\n"
        )
        out.append(f"- **Author**: {rule.author}, pack `{rule.pack}`, rule version {rule.version}\n")
        out.append("- **Facts it needs**: `{}`\n".format("`, `".join(rule.needs)))
        out.append(f"- **Remediation it suggests**: {rule.remediation}\n")
        if rule.marked:
            out.append(
                f"- **NO REAL VIOLATION**: {rule.no_real_violation}. The violating test runs "
                "on the configuration the vendor publishes, not on a repository that does "
                "this.\n"
            )
            if rule.violation_source:
                out.append(
                    f"  - Case taken from <{rule.violation_source}>, sha256 "
                    f"`{rule.violation_source_sha256}`, read "
                    f"{rule.violation_source_consulted}\n"
                )
            for search in rule.searches:
                out.append(
                    f"  - Searched `{search.query}` on {search.date}: "
                    f"{search.results} result(s), {search.violating} violating\n"
                )
        if rule.atr:
            out.append("- **Agent Threat Rules**: {}\n".format(", ".join(rule.atr)))
        if rule.references:
            out.append("- **References**:\n")
            for link in rule.references:
                out.append(f"  - <{link}>\n")

    out.append(
        "\n---\n\nNot firing is not safety. A repository can have no finding here and be "
        "badly configured for a reason no rule names; that is published limit 9 and it is "
        "printed in the report as well as written here.\n"
    )
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail instead of rewriting, which is what the gate runs")
    args = parser.parse_args()

    wanted = render()
    if args.check:
        if not PAGE.is_file():
            print("docs/RULES.md is missing. Run `make rules`.", file=sys.stderr)
            return 1
        if PAGE.read_text(encoding="utf-8") != wanted:
            print(
                "docs/RULES.md is not the page this tree produces. Run `make rules` and "
                "commit the result.",
                file=sys.stderr,
            )
            return 1
        print("docs/RULES.md is current")
        return 0

    PAGE.write_text(wanted, encoding="utf-8")
    from actaira.surface import rules as rule_module

    print(f"wrote docs/RULES.md: {len(rule_module.load())} rules")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
